course = 'Python for Beginners'
# print(course.upper())
# print(course.lower())
# print(course)
# print(course.find('P'))
# print(course.find('o'))
# print(course.find('O'))
# print(course.replace('Beginners', 'Absolute Beginners'))
# print(course.replace('P', 'J'))
# print(course.replace('o', 'i'))
# print('Python' in course)
print('python' in course)
